In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("./Resources.csv")
df

In [ ]:
df.columns

In [ ]:
df.columns = ["No.", "Title", "URL", "Status"]
df.columns

In [ ]:
df.head(5)

In [ ]:
df.tail(5)

In [ ]:
df = df.dropna(subset=['No.'], axis=0)
df.head(10)

In [ ]:
df.to_csv("./new_csv.csv", index=False)

In [ ]:
df_new = pd.read_csv("./new_csv.csv")

In [ ]:
df_new.head(10)

In [18]:
df.dtypes

No.       str
Title     str
URL       str
Status    str
dtype: object

In [20]:
df.describe()

,No.,Title,URL,Status
count,37,34,34,0
unique,15,34,34,0
top,1,The Beginner's Guide to Digital Art,https://youtu.be/O40KGoCmpNA,NaN
freq,4,1,1,NaN

In [21]:
df.describe(include = "all")

,No.,Title,URL,Status
count,37,34,34,0
unique,15,34,34,0
top,1,The Beginner's Guide to Digital Art,https://youtu.be/O40KGoCmpNA,NaN
freq,4,1,1,NaN

In [28]:
df["No."].head(10)

0                1
1                2
3     FUNDAMENTALS
5                1
6                2
7                3
8                4
9                5
10               6
11               7
Name: No., dtype: str

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 37 entries, 0 to 42
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   No.     37 non-null     str
 1   Title   34 non-null     str
 2   URL     34 non-null     str
 3   Status  0 non-null      str
dtypes: str(4)
memory usage: 3.6 KB